# Generated by Django 5.0.7 on 2024-07-17 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_tudo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tudo_list_model',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tudo_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_work', models.TextField(max_length=250)),
                ('user_tudo_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_tudo.user_model')),
            ],
        ),
    ]
